version: '3.3'

services:
  web:
    image: registry.gitlab.com/webnazakazku/prebuild-php:8.0-apache
    volumes:
      - ./:/var/www/html
      - ./.docker/apache/sites-enabled:/etc/apache2/sites-enabled
      - ./.docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./.docker/cache:/cache
    ports:
      - '80:80'

  database:
    image: mariadb:latest
    volumes:
      - ./.docker/database/data:/var/lib/mysql
      - ./.docker/database/initDb.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: is
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: is

  adminer:
    image: adminer:4.6
    ports:
      - '8081:8080'
    environment:
      ADMINER_DEFAULT_SERVER: database

  composer:
    image: composer:latest
    volumes:
      - ./:/app
      - ./.docker/cache:/cache
    working_dir: /app
    command: composer install --ignore-platform-reqs

  console:
    image: ghcr.io/webnazakazku/docker-php-build:8.0
    entrypoint: bash
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./.docker/cache:/cache
      - ./.docker/console/root:/root
